ci (scripts): fix scripts

diff --git a/ci/smoke-test b/ci/smoke-test
--- a/ci/smoke-test
+++ b/ci/smoke-test
@@ -1,4 +1,6 @@
 #!/usr/bin/env bash
+set -e
+set -o pipefail
 
 get_app_name() {
     [ "$1" = "yes" ] && echo $HEROKU_APP_NAME || echo $HEROKU_APP_NAME_STAGING
@@ -20,20 +22,25 @@ APP_NAME=$(get_app_name $IS_PROD)
 
 if [[ $IS_PROD == "yes" ]]; then
     TARGET_URL="https://$HEROKU_APP_NAME.herokuapp.com"
-    PACKAGE_VERSION=$PACKAGE_VERSION_TARGET
 elif [[ $IS_PROD == "no" ]]; then
     TARGET_URL="https://$HEROKU_APP_NAME_STAGING.herokuapp.com"
+fi
+
+if [[ $IS_PROD == "yes" || "$CIRCLE_BRANCH" == "master" ]]; then
+    PACKAGE_VERSION=$PACKAGE_VERSION_TARGET
+elif [[ $IS_PROD == "no" ]]; then
     PACKAGE_VERSION=$(jq -r ".version" < package.json)
 fi
 
 PRODUCTION_VERSION_IN_HTML=$(curl -s $TARGET_URL | grep -iPo "(?<=\|\s).+(?=</title>)")
 
 if [[ $PACKAGE_VERSION == $PRODUCTION_VERSION_IN_HTML ]]; then
-  echo "SMOKE TEST PASSED FOR $TARGET_URL: \
-    ACTUAL VERSION DEPLOYED $PRODUCTION_VERSION_IN_HTML \
-    PACKAGE VERSION FOR DEPLOYMENT $PACKAGE_VERSION"
+  echo "SMOKE TEST PASSED FOR $TARGET_URL:"
+  echo "ACTUAL VERSION DEPLOYED $PRODUCTION_VERSION_IN_HTML"
+  echo "PACKAGE VERSION FOR DEPLOYMENT $PACKAGE_VERSION"
 else
-  echo "SMOKE TEST FAILED FOR $TARGET_URL: \
-    ACTUAL VERSION DEPLOYED $PRODUCTION_VERSION_IN_HTML \
-    PACKAGE VERSION FOR DEPLOYMENT $PACKAGE_VERSION"
+  echo "SMOKE TEST FAILED FOR $TARGET_URL:"
+  echo "ACTUAL VERSION DEPLOYED $PRODUCTION_VERSION_IN_HTML"
+  echo "PACKAGE VERSION FOR DEPLOYMENT $PACKAGE_VERSION"
+  exit 1
 fi
